server:
  addr: ":8080"
  model: "debug"
log:
  file: "credit-api.log"
  level: "debug"
db:
  host: "192.168.1.125"
  port: 3306
  username: "root"
  password: "123456"
  database: "credit"
  maxOpenConn: 50
  maxIdleConn: 10
api:
  minivision:
    url: "http://8.219.215.61:58682"
    appKey: "7c060867c16cf84c87710cf4576e4ea0"
    appSecret: "xskj2019"